export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_THIS_PROFILE = "GET_THIS_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_VIEWED = "PROFILE_VIEWED";
export const GET_REPOS = "GET_REPOS";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const GET_SUGGESTIONS = "GET_SUGGESTIONS";
export const GET_MOST_VIEWED_PEOPLE = "GET_MOST_VIEWED_PEOPLE";
export const GET_MOST_TALENTED_PEOPLE = "GET_MOST_TALENTED_PEOPLE";
export const PROFILE_REPORTED = "PROFILE_REPORTED";

export const RESET_PASSWORD_MAIL = "RESET_PASSWORD_MAIL";
export const NEW_PASSWORD_MAIL = "NEW_PASSWORD_MAIL";
export const MAIL_FAILED = "MAIL_FAILED";

export const AVATAR_UPDATED = "AVATAR_UPDATED";
export const COVER_UPDATED = "COVER_UPDATED";

export const ADD_REVIEW = "ADD_REVIEW";

export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";

export const NOTIFY = "NOTIFY";

// post types
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";

export const UPDATE_LIKES = "UPDATE_LIKES";
export const VIEWED = "VIEWED";

export const DELETE_POST = "DELETE_POST";
export const DELETE_SHARE = "DELETE_SHARE";

export const ADD_POST = "ADD_POST";
export const UPDATE_POST = "UPDATE_POST";
export const SAVED_POST = "SAVED_POST";
export const UNSAVED_POST = "UNSAVED_POST";
export const POST_HIDDEN = "POST_HIDDEN";
export const UNHIDE_POST = "UNHIDE_POST";

export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const ADD_REPORT = "ADD_REPORT";

export const SHARE_POST = "SHARE_POST";

export const SEND_POST_MAIL = "SEND_POST_MAIL";

// Question types
export const GET_QUESTIONS = "GET_QUESTIONS";
export const CREATE_QUESTIONS = "CREATE_QUESTIONS";
export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
export const CREATE_ANSWER = "CREATE_ANSWER";
export const QUESTION_ERROR = "QUESTION_ERROR";
export const CREATE_REPLY = "CREATE_REPLY";
export const SOLUTION = "SOLUTION";
export const UPVOTE = "UPVOTE";
export const CANCEL_UPVOTE = "CANCEL_UPVOTE";
export const DOWNVOTE = "DOWNVOTE";
export const CANCEL_DOWNVOTE = "CANCEL_DOWNVOTE";
export const CREATE_ANSWER_REPORT = "CREATE_ANSWER_REPORT";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const DELETE_REPLY = "DELETE_REPLY";
export const SORT_ANSWERS = "SORT_ANSWERS";
export const UPVOTE_ANSWER = "UPVOTE_ANSWER";
export const DOWNVOTE_ANSWER = "DOWNVOTE_ANSWER";
export const DOWNVOTE_REPLY = "DOWNVOTE_REPLY";
export const UPVOTE_REPLY = "UPVOTE_REPLY";
export const ADD_VIEW = "ADD_VIEW";
export const SORT_ANSWERS_VOTES = "SORT_ANSWERS_VOTES";
export const SORT_QUESTIONS = "SORT_QUESTIONS";
export const FILTER_QUESTIONS = "FILTER_QUESTIONS";
export const SEARCH_QUESTIONS = "SEARCH_QUESTIONS";
export const FOLLOW_QUESTION = "FOLLOW_QUESTION";
export const UNFOLLOW_QUESTION = "UNFOLLOW_QUESTION";
export const GET_FOLLOWED_QUESTIONS = "GET_FOLLOWED_QUESTIONS";
export const UPVOTE_QUESTION = "UPVOTE_QUESTION";
export const DOWNVOTE_QUESTION = "DOWNVOTE_QUESTION";
export const YOUTUBE_REC = "YOUTUBE_REC";
export const BLOG_REC = "BLOG_REC";
export const NEWS_REC = "NEWS_REC";
export const NEWS_REC_SKILLS = "NEWS_REC_SKILLS";
export const SAVE_NEWS = "SAVE_NEWS";
export const GET_SAVED_NEWS = "GET_SAVED_NEWS";
export const CANCEL_NEWS = "CANCEL_NEWS";
export const ADD_DOMAIN = "ADD_DOMAIN";
export const GET_DOMAINS = "GET_DOMAINS";
export const CANCEL_DOMAIN = "CANCEL_DOMAIN";
export const UPDATE_QUESTIONS = "UPDATE_QUESTIONS";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const GET_SETTING = "GET_SETTING";
export const GET_BLOCK = "GET_BLOCK";
export const GET_ALL_DOMAINS = "GET_ALL_DOMAINS";
export const GET_SCORES = "GET_SCORES";

// Scrapig types
export const SCRAPE_STACKOVERFLOW = "SCRAPE_STACKOVERFLOW";
export const GET_STACKOVERFLOW_SCRAPED_DATA = "GET_STACKOVERFLOW_SCRAPED_DATA";
export const SCRAPING_ERROR = "SCRAPING_ERROR";
export const SCRAPE_TANITJOB = "SCRAPE_TANITJOB";
export const GET_TANITJOB_SCRAPED_DATA = "GET_TANITJOB_SCRAPED_DATA";
export const GET_INDEED_SCRAPED_DATA = "GET_INDEED_SCRAPED_DATA";
export const GET_FREECOURSE_SCRAPED_DATA = "GET_FREECOURSE_SCRAPED_DATA";
export const GET_EDX_SCRAPED_DATA = "GET_EDX_SCRAPED_DATA";

// job types

export const GET_JOBS = "GET_JOBS";

export const GET_JOB = "GET_JOB";

export const DELETE_JOB = "DELETE_JOB";

export const ADD_JOB = "ADD_JOB";

export const UPDATE_JOB = "UPDATE_JOB";

export const JOB_ERROR = "JOB_ERROR";

export const UPDATE_LIKE = "UPDATE_LIKE";

export const CLEAR_CURRENT = "CLEAR_CURRENT";

export const SET_CURRENT = "SET_CURRENT";

export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_LOADING = "SET_LOADING";

export const SET_ACTIVE = "SET_ACTIVE";

export const SET_DISACTIVE = "SET_DISACTIVE";

export const UPDATE_SAVE_JOB = "UPDATE_SAVE_JOB";

export const ADD_VIEWS = "ADD_VIEWS";

export const ADD_COMME = "ADD_COMME";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const SEARCH_PRICE = "SEARCH_PRICE";

export const SEARCH_JOB_TYPE = "SEARCH_JOB_TYPE";

export const SEARCH_COUNTRY = "SEARCH_COUNTRY";

export const SEARCH_AVAILABILITY = "SEARCH_AVAILABILITY";

export const SEARCH_SKILLS = "SEARCH_SKILLS";

export const GET_JOBS_BY_USER = "GET_JOBS_BY_USER";

export const ADD_CANDIDATE = "ADD_CANDIDATE";

export const DELETE_CANDIDATE = "DELETE_CANDIDATE";

export const JOB_APPLY = "JOB_APPLY";

export const SET_ACTIVE_REPORT = "SET_ACTIVE_REPORT";

export const SET_DISACTIVE_REPORT = "SET_DISACTIVE_REPORT";

export const ADD_REP = "ADD_REP";

export const SET_ACTIVE_MAIL = "SET_ACTIVE_MAIL";

export const SET_DISACTIVE_MAIL = "SET_DISACTIVE_MAIL";

export const ADD_MAIL = "ADD_MAIL";

export const ADD_INTERVIEW = "ADD_INTERVIEW";
